### ISSUE TITLE
Manual testing: toolbox-streams on dev

### ISSUE THREAD

**Issue by joschne** [geovistory/toolbox-streams#58]
**Goal**

The toolbox-streams application is tested manually via user interface on dev environment according to the guidelines for testing Geovistory Toolbox.

**Output**

A test report on the internal confluence page.

**Comment by gaetanmuck** [comment]
Done, 

https://kleiolab.atlassian.net/wiki/spaces/GEOV/pages/3425796132/Test+Toolbox+streams+2
