### ISSUE TITLE
ensure time primitives & appellations are displayed in "analysis - table"

### ISSUE THREAD

**Issue by KleiolabDK** [geovistory/toolbox-streams#87]
With the migration of the toolbox to kafka streams, the tables produced in the toolbox doe not display anymore time primitives.

See screenshot:

![Image](https://user-images.githubusercontent.com/51605237/235354054-b17b9d41-29a0-4859-9e20-094bdfdcf465.png)

It would be important that time primitives are visualized again.

**Comment by KleiolabDK** [comment]
along the same line, time primitives are not taken into account in the labels:



![Image](https://user-images.githubusercontent.com/51605237/235362195-e851a4cd-0b82-492b-8fd1-1a344f9c05a9.png)

**Comment by KleiolabDK** [comment]
again, maybe linked to the same issue, also other "values" like appellation, behave as time primitives and are not displayed in the anaylsis tables. See here:



![Image](https://user-images.githubusercontent.com/51605237/235409290-6257a8ae-b126-43a9-ab8f-85f3bcdf7e74.png)

**Comment by joschne** [comment]
I split the different comments in separate issues:

Comment 1: causes #90 
Comment 2: causes #91
Comment 3: causes #92

@KleiolabDK let's continue the discussion on the new issues
