### ISSUE TITLE
labels & classes in project "La déportation des Roms en Transnistrie" seem to be systematically missbehaving

### ISSUE THREAD

**Issue by KleiolabDK** [geovistory/toolbox-streams#89]
It seems that after the kafka-toolbox update some stuff in the EHESS/Deportation project is not right anymore (or hiddenly never was).

The symptom to be observed easiest is, that many entities appear to be “zombies”, hence without label. This happened also in other projects, but there, it was few and to be resolved easily. Here, it seems more systematical problem.

Find below the results of my fast investigation. I hope this is helpful.

------------------------------------------------

See the screenshot below of a **person without label**:
 

![Image](https://user-images.githubusercontent.com/51605237/235409505-e643a575-8c4d-4763-9589-a0a7eff218df.png)

-> A short investigation shows that most likely this entity appears without label because the “Person appellation in a language”, which is label-defining, is not in the project (clicking on it I could add it, which I did not do). Also the external identifiers and the localization below behave the same way.

Checking more generally via the analysis tab, I find that likle no localization for example is within the project, all rows are empty:
 

 The same is true for the **archival references**:
 

![Image](https://user-images.githubusercontent.com/51605237/235409484-3cd4c575-48ec-4b4d-aca9-03d6e7f6e2bd.png)

When it comes to **identifiers**, many persons show 2 identifiers of which only 1 is within the project, like this one:
 

![Image](https://user-images.githubusercontent.com/51605237/235409470-3cb64c1b-6778-4266-af6d-63a7b227d167.png)

In general, “only” 4008 of all persons have currently an identifier.:
 

![Image](https://user-images.githubusercontent.com/51605237/235409462-50b09269-fe40-4a61-a8fd-e96ac342c99c.png)

**Comment by gaetanmuck** [comment]
Data changed

**Comment by KleiolabDK** [comment]
@gaetanmuck it generally looks good thanks! there are some 12 zombie "births", lets check them together today.

**Comment by joschne** [comment]
closing as done
