### ISSUE TITLE
Missing time primitives in analysis

### ISSUE THREAD

**Issue by joschne** [geovistory/toolbox-streams#90]
With the migration of the toolbox to kafka streams, the tables produced in the toolbox doe not display anymore time primitives.

See screenshot:

![Image](https://user-images.githubusercontent.com/51605237/235354054-b17b9d41-29a0-4859-9e20-094bdfdcf465.png)

It would be important that time primitives are visualized again.

**Comment by joschne** [comment]
@KleiolabDK this bug is resolved in my opinion, can you confirm and close, if ok.

**Comment by KleiolabDK** [comment]
ok
