### ISSUE TITLE
Values not showing in analysis

### ISSUE THREAD

**Issue by joschne** [geovistory/toolbox-streams#91]
"values" like appellation, behave as time primitives and are not displayed in the anaylsis tables. See here:

![Image](https://user-images.githubusercontent.com/51605237/235409290-6257a8ae-b126-43a9-ab8f-85f3bcdf7e74.png)

**Comment by joschne** [comment]
@KleiolabDK this bug is resolved in my opinion, can you confirm and close, if ok.

**Comment by KleiolabDK** [comment]
yes, confirmed. I think the ticket is already closed. thanks!
